<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pembeli_model extends CI_Model
{

    public $table = 'pembeli';
    private $tb_pembeli='pembeli';
    public $id = 'id_pembeli';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->load->library('m_db');
    }

    function pembeli_data($where=array(),$order="nama_pembeli ASC")
    {
        $d=$this->m_db->get_data($this->tb_pembeli,$where,$order);
        return $d;
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pembeli', $q);
	$this->db->or_like('nama_pembeli', $q);
	$this->db->or_like('usia', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('penghasilan', $q);
    $this->db->or_like('riwayat_kredit', $q);
	$this->db->or_like('uang_muka', $q);
	$this->db->or_like('jangka_waktu', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('no_telpon', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pembeli', $q);
	$this->db->or_like('nama_pembeli', $q);
	$this->db->or_like('usia', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('penghasilan', $q);
	$this->db->or_like('riwayat_kredit', $q);
	$this->db->or_like('uang_muka', $q);
	$this->db->or_like('jangka_waktu', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('no_telpon', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pembeli_model.php */
/* Location: ./application/models/Pembeli_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-23 05:12:40 */
/* http://harviacode.com */